name: CI TESTS

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Suite
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest]
    steps:
      - name: Hello World
        run: echo "Hello World"
